server:
  port: 20001
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: login-server
          uri: http://127.0.0.1:20002
          predicates:
            - Path=/login/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:20000/eureka/
